Asynchronous sendStatus(), pass WAL position to handler, fix plugin args
kyleconroy/pgoutput pull request #2
Opened 2018-07-04 12:37 UTC by blind-oracle

Thanks for a very good work on pgoutput.
Some changes that I did for our project that may be useful to somebody and maybe worth integrating to the base project.

* Send status to the PostgreSQL asynchronously - useful when the handler takes a long time to process an event
* Pass WAL position to handler (in case it needs to track it)
* Add the ability to specify starting WAL position and skip the log events from past if PostgreSQL sends them for some reason
* Some bug fixes like ticker leakage
* Don't remove replication slot as the WAL position is tracked there

2018-10-22 17:52 UTC, jmealo commented
@kyleconroy @blind-oracle great collaboration! any chance we can get this merged upstream? Thank you for your hard work!

2018-10-22 17:55 UTC, kyleconroy commented
@jmealo sure! I honestly had forgotten about this pull request 😬 

@blind-oracle do you have time to make some changes? I know this code is from a while back.

2018-10-22 17:57 UTC, kyleconroy requested changes
Overall these changes look great. Can you walk me through why you've deleted the vendored code?

2018-10-22 17:57 UTC, kyleconroy commented on examples/replicate.go
> +	"github.com/blind-oracle/pgoutput"
I know this is useful for testing, but this needs to be reverted before merging.

2018-10-22 17:57 UTC, kyleconroy commented on examples/replicate.go
> +	sub := pgoutput.NewSubscription(conn, "sub1", "pub1", 1048576)
I know this is just an example, but can we reset the offset value here to zero?

2018-10-22 19:37 UTC, blind-oracle commented
Sorry, I also forgot about it and kept committing our project-specific stuff to my fork that ended up here :)
I'll take time to clean it up in a few days and fix @kyleconroy 's notes.

Regarding vendor folder - I had conflicts between different version of libraries (pgoutput's vs our project's) if I remember correctly. Some points against committing vendor to repo also here https://github.com/golang/dep/blob/master/docs/FAQ.md#my-dependers-dont-use-dep-yet-what-should-i-do

And if you take a look at most other popular libraries - they don't commit *vendor* folder to repo. Maybe we should just use *dep*'s Gopkg.toml/.lock instead if we need to pin specific versions.

2018-10-22 20:06 UTC, kyleconroy commented
Makes sense about the vendor directory, as this is a library. Instead of committing a Gopkg.* file, I think I'll just tag a `0.1.0` release and add a `go.mod` file.

2018-10-23 08:45 UTC, blind-oracle commented
Ok I've done some modifications & fixes, it should be Ok now. But since the API was changed probably we want to retain current version under some tag.

2018-10-23 18:35 UTC, jmealo commented
Thanks for looking into this!

2018-12-30 20:24 UTC, blind-oracle commented
Any chance this would be merged?

2018-12-30 21:48 UTC, kyleconroy approved these changes

2018-12-30 21:48 UTC, merged